/* index.svelte.js generated by Svelte v5.2.7 */
import * as $ from "svelte/internal/client";

function media(query, match = true, nomatch = false) {
	let state = $.state($.proxy(nomatch));

	if (typeof window !== 'undefined') {
		const mql = window.matchMedia(query);

		mql.onchange = (ev) => $.set(state, $.proxy(ev.matches ? match : nomatch));
		$.set(state, $.proxy(mql.matches ? match : nomatch));
	} else {
		$.set(state, $.proxy(nomatch));
	}

	return {
		get current() {
			return $.get(state);
		}
	};
}

export default media;

export const reduced = (match = true, nomatch = false) => media('(prefers-reduced-motion)', match, nomatch);
export const darkmode = (match = true, nomatch = false) => media('(prefers-color-scheme: dark)', match, nomatch);
